spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          username: ${CONFIG_GIT_USERNAME:}
          password: ${CONFIG_GIT_PASSWORD:}
          default-label: ${CONFIG_GIT_LABEL:prod}
          clone-on-start: true
          force-pull: true
          timeout: 10
  security:
    user:
      name: ${CONFIG_SERVER_USER:configadmin}
      password: ${CONFIG_SERVER_PASSWORD:}

payconfig-server:
  security:
    basic-auth-enabled: true
